### ISSUE TITLE
Error on changing permissions of a new group with MongoDB

### ISSUE THREAD

**Issue by synthecypher** [COCOPi/cockpit#481]
**Steps to reproduce**

1. Setup Cockpit CMS with `php5-fpm` and `nginx`.
2. Create a new user group with name `employee`.
3. Add a permission to group `employee`.
4. Click **Save**.
5. Alert will show
> Uuups, something went wrong...
6. This should show in the log.
```
==> /var/log/nginx/error.log <==
2016/11/09 11:37:46 [error] 43#0: *283 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'MongoWriteConcernException' with message 'mongodb:27017: The dotted field 'manage.backups' in 'val.admin.Cockpit.manage.backups' is not valid for storage.' in /var/www/cockpit/vendor/MongoHybrid/Mongo.php:107
Stack trace:
#0 /var/www/cockpit/vendor/MongoHybrid/Mongo.php(107): MongoCollection->save(Array)
#1 /var/www/cockpit/vendor/MongoHybrid/Client.php(77): MongoHybrid\Mongo->save('cockpit/setting...', Array)
#2 /var/www/cockpit/modules/core/Auth/Controller/Accounts.php(178): MongoHybrid\Client->setKey('cockpit/setting...', 'cockpit.acl.rig...', Array)
#3 [internal function]: Auth\Controller\Accounts->saveAcl()
#4 /var/www/cockpit/vendor/Lime/App.php(1009): call_user_func_array(Array, Array)
#5 /var/www/cockpit/vendor/Lime/App.php(786): Lime\App->invoke('Auth\\Controller...', 'saveAcl', Array)
#6 [internal function]: LimeExtra\App->Lime\{closure}(Array)
#7 /var/www/cockpit/vendor/Lime/App.php(986): call_user_func(Object(Closure), Array)
#8 /var/www/cockp" while reading response header from upstream, client: 172.19.0.1, server: _, request: "POST /cockpit/accounts/saveAcl HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:"
```

**Comment by aheinze** [comment]
does this issue still exist?

**Comment by synthecypher** [comment]
If you couldn't reproduce it then I get mark it as can't reproduce and
close the issue.
