### ISSUE TITLE
Rest API - Regions

### ISSUE THREAD

**Issue by Escapado** [COCOPi/cockpit#550]
Hello, 
I'd like to access the fields of a region (named "startseite") I created. I found a closed issue #493 and in the comments it was mentioned how to access the data. I would like to avoid filling a template with JSON markup if possible.

However if I do a get request on 
```
http://localhost:8888/cockpit/api/regions/data/startseite?token=ed132ec30a38cb383e31651a30686e
```
I get the following error:

```
{
    "type": 1,
    "message": "Uncaught Error: Cannot use object of type Regions\\Controller\\RestApi as array in \/Users\/kevin.peters\/WebRoot\/cockpit\/modules\/Regions\/Controller\/RestApi.php:36\nStack trace:\n#0 [internal function]: Regions\\Controller\\RestApi->data('Startseite')\n#1 \/Users\/kevin.peters\/WebRoot\/cockpit\/lib\/Lime\/App.php(1061): call_user_func_array(Array, Array)\n#2 \/Users\/kevin.peters\/WebRoot\/cockpit\/modules\/Cockpit\/rest-api.php(94): Lime\\App->invoke('Regions\\\\Control...', 'data', Array)\n#3 [internal function]: LimeExtra\\App->{closure}(Array)\n#4 \/Users\/kevin.peters\/WebRoot\/cockpit\/lib\/Lime\/App.php(1038): call_user_func(Object(Closure), Array)\n#5 \/Users\/kevin.peters\/WebRoot\/cockpit\/lib\/Lime\/App.php(985): Lime\\App->render_route('\/api\/*', Array)\n#6 \/Users\/kevin.peters\/WebRoot\/cockpit\/lib\/Lime\/App.php(942): Lime\\App->dispatch('\/api\/regions\/da...')\n#7 \/Users\/kevin.peters\/WebRoot\/cockpit\/index.php(37): Lime\\App->run()\n#8 {main}\n  thrown",
    "file": "\/Users\/kevin.peters\/WebRoot\/cockpit\/modules\/Regions\/Controller\/RestApi.php",
    "line": 36
}
```
I am running Version `0.3.7`

**Comment by aheinze** [comment]
Cockpit legacy isn't supported anymore, please use Cockpit Next.
